# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

best_cut_node <- function(method, lambda, Data, Labels, W, minleaf, numLabels) {
    .Call(`_ODRF_best_cut_node`, method, lambda, Data, Labels, W, minleaf, numLabels)
}

ppOptCpp <- function(y, X, q = 1L, PPmethod = "LDA", weight = TRUE, r = 1L, lambda = 0.1, energy = 0, cooling = 0.999, TOL = 0.0001, maxiter = 50000L) {
    .Call(`_ODRF_ppOpt`, y, X, q, PPmethod, weight, r, lambda, energy, cooling, TOL, maxiter)
}

predict_ODT <- function(Data, nodeRotaMat, nodeCutValue, childNode, nodeLabel) {
    .Call(`_ODRF_predict_ODT`, Data, nodeRotaMat, nodeCutValue, childNode, nodeLabel)
}

