# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BODTCpp <- function(X, y, Xtest, Y, numClass = 1L, maxTerms = 100L, ntrees = 100L, mtry = 1L, MinLeaf = 5L, replacement = TRUE, ratOOB = 0.37) {
    .Call(`_ODRF_GBDT`, X, y, Xtest, Y, numClass, maxTerms, ntrees, mtry, MinLeaf, replacement, ratOOB)
}

best_cut_node <- function(method, lambda, Data, Labels, W, minleaf, numLabels) {
    .Call(`_ODRF_best_cut_node`, method, lambda, Data, Labels, W, minleaf, numLabels)
}

ppOptCpp <- function(y, X, q = 1L, PPmethod = "LDA", weight = TRUE, r = 1L, lambda = 0.1, energy = 0, cooling = 0.999, TOL = 0.0001, maxiter = 50000L) {
    .Call(`_ODRF_ppOpt`, y, X, q, PPmethod, weight, r, lambda, energy, cooling, TOL, maxiter)
}

predict_ODT <- function(Data, nodeRotaMat, nodeCutValue, childNode, nodeLabel) {
    .Call(`_ODRF_predict_ODT`, Data, nodeRotaMat, nodeCutValue, childNode, nodeLabel)
}

